version: "3.8"
services:
  springboot-app:
    image: kemchhai093/docker_jenkins_springboot:${BUILD_NUMBER}
    ports:
      - "8082:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
